name: Build and release
on:
  push:
    tags:
      - '*'

jobs:
  release-macos:
    name: Release macOS app
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Create app with pyinstaller
        run: pyinstaller --windowed --name "Study Planner" --icon icons/icon_square.png main.py
      - name: Compress app to archive
        run: |
          cd dist
          zip -r StudyPlanner.app.zip Study\ Planner.app
          cd ..
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/StudyPlanner.app.zip
          asset_name: study-planner-macos-x86_64_$tag.zip
          tag: ${{ github.ref }}

  release-windows:
    name: Release Windows app
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Create app with pyinstaller
        run: pyinstaller --windowed --name "Study Planner" --add-data icons;icons --icon icons\icon_round.ico --onefile main.py
        shell: cmd
      - name: Compress app to archive
        run: |
         cd dist
         tar -a -c -f StudyPlanner.zip "Study Planner.exe"
         cd ..
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist\StudyPlanner.zip
          asset_name: study-planner-windows-x86_64_$tag.zip
          tag: ${{ github.ref }}

  release-gnulinux:
    name: Release on GNU/Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Create app with pyinstaller
        run: pyinstaller --windowed --name "Study Planner" --add-data icons:icons --icon icons/icon_round.ico --onefile main.py
      - name: Compress app to archive
        run: |
          cd dist
          tar -czf StudyPlanner.tar.gz Study\ Planner
          cd ..
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/StudyPlanner.tar.gz
          asset_name: study-planner-gnulinux-x86_64_$tag.tar.gz
          tag: ${{ github.ref }}
